### ISSUE TITLE
Doesn't seem to work as expected.

### ISSUE THREAD

**Issue by dextermb** [ForbesLindesay/express-route-tester#10]
Hey there,

I'm attempting to get some of my routing to work using regex. I came across this repo which is meant to help with testing... but it fell over on the first hurdle.

Here's a basic example:

This route is valid for express, only allowing digit characters:
```/user/:id(\\d+)```

But when testing in the _route tester_ it says that it is invalid until I remove the first backslash:
```/user/:id(\d+)```

But then it becomes invalid for express.

As you might of noticed, I am writing this route to only except user IDs. But I want a separate route to only except usernames. Here's what I have so far:

```/user/:username(\\b\w*[a-zA-Z]+\w\b)```

This doesn't seem to work in express or the _route tester_. So I'm at a loss now.

Regards,
Dexter

**Comment by ForbesLindesay** [comment]
The extra `\` is required because you are writing it in JavaScript source code, where strings need escaping.  The express-rotue-tester expects the literal text.
