### ISSUE TITLE
it don't work

### ISSUE THREAD

**Issue by Sequoia** [ForbesLindesay/express-route-tester#6]
route: `/admin`
path: `/admin/foo`
- Expected: :white_check_mark: 
- Actual: :x: :point_left: incorrect

---

route: `/admin/*`
path: `/admin/foo`
- Expected: :white_check_mark: 
- Actual: :x: :point_left: incorrect

Etc.

**Comment by rjmunro** [comment]
So although this is called "express-route-tester" it should actually be called "path-to-regexp" tester (https://www.npmjs.com/package/path-to-regexp). Express uses "path-to-regexp", but at a *very* old version (0.1.7), which has different behaviour for `*`.

Unfortunately Express' documentation says to use this tool, which has been updated. Ideally the tool could have a switch to choose the old or new dialect - there is a PR that does this (https://github.com/ForbesLindesay/express-route-tester/pull/11) and you can use it here: https://wesleytodd.github.io/express-route-tester/

**Comment by ForbesLindesay** [comment]
This is now fixed
