### ISSUE TITLE
Unescaped backslashes still work

### ISSUE THREAD

**Issue by ki9us** [ForbesLindesay/express-route-tester#7]
According to the [path-to-regexp docs](https://www.npmjs.com/package/path-to-regexp#custom-match-parameters), "Backslashes need to be escaped in strings."

But the tester works if I put in something like `\d` for route and `4` for path.  It should only work with `\\d`, which doesn't work at all.  But that's how it is in _real_ express.js routing.

**Comment by wesleytodd** [comment]
`express@4` uses `path-to-regexp@0.1.7` and this was using `path-to-regexp@1.0.1`.  So they will work different.  If #11 merges, then you can test to actual express version.  In the mean time, you can use https://wesleytodd.github.io/express-route-tester/
