### ISSUE TITLE
Wrong value shown for missing optional arguments

### ISSUE THREAD

**Issue by georgir** [ForbesLindesay/express-route-tester#8]
If you enter a route with an optional argument and a test path that has a value for it first, and then one that has not, the second test will still show the value from the first test.

**Comment by asokani** [comment]
You are right. This is a test:
Route: `/test/:key?`
First fill in this:
Path: `/test/blah`
and then change the path to:
Path: `/test`

**Comment by wesleytodd** [comment]
I believe this is fixed in #11. You can check here: https://wesleytodd.github.io/express-route-tester/

If they merge that up maybe you can close this.
